version: '3.8'
services:
  mongodb:
    image: mongo:7
    container_name: pulseconnect-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=pulseconnect
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1
    container_name: pulseconnect-mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH=false
    ports:
      - "8087:8081"
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local
